version: '3.8'

services:

  products:
    image: products
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=productdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/productdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    networks:
      - microservices-network
    depends_on:
      - mysql
      - config-server
      - eureka
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    

  order:
    image: order
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=orderdb
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network
    depends_on:
      - mongo
      - config-server
      - eureka
      - api-gateway
  stock:
    image: stock
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=stock
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network
    depends_on:
      - mongo
      - config-server
      - eureka
      - api-gateway

  api-gateway:
    image: apigateway
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network
    depends_on:
      - eureka
      - config-server

  eureka:
    image: eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
   image: hyness/spring-cloud-config-server
   environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:-https://github.com/yassinebouharb/config}"
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: "sagemcom66"
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
   ports:
      - 8888:8888
   networks:
      - microservices-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - microservices-network

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=productsdb
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
