spring:
  application:
    name: Stock
  data:
    mongodb:
      uri: mongodb://mongo:27017/stock
  cloud:
    config:
      uri: http://config-server:8888
      name: stock
      profile: dev
      label: main
      import: config-server
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

